# Generated by Django 3.2.4 on 2023-01-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_auto_20230101_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
    ]
